# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
permalink:           pretty

# Setup
title:              "Cydu's Blog"
tagline:            "Keep it Simple & Stupid!"
description:        "Chuanying Du"
url:                http://cydu.github.io/blog.cydu.net/
baseurl:            /
paginate:           20

# About/contact
author:
  name:             Chuanying Du
  short_name:       cydu
  linkedin:         http://cn.linkedin.com/in/chuanying

# Custom vars
version:             1.0.1

theme: jekyll-theme-minimal
